### ISSUE TITLE
MapReduce & Hadoop

### ISSUE THREAD

**Issue by mukulsalhotra** [mukulsalhotra/BD2017#1]

**Comment by HorizonNet** [comment]
Below is a short review.

**Tasks**

- [x]  Download a book text from the Gutenberg Project and copy it into HDFS
- [ ] Write a MapReduce program that does a WordCount on an arbitrary text file
- [ ] Package your WordCount application into a Maven project and build it
- [ ] Using `teragen` and `terasort`

Below are a few comments/suggestions:

* You should not commit stuff directly in GitHub, like you did in this [commit](https://github.com/mukulsalhotra/BD2017/commit/53df42084eb697fbdb18d62879efb777a7e3be74). This can easily lead to conflicts if you make changes to your local repository without pulling first. Also, with this approach you don't have a local copy of your repository without pulling it from GitHub.
* When working with HDFS you should use `hdfs dfs` instead of `hadoop fs` or `hadoop dfs`. This will give you some more HDFS-specific commands. The other two are there in case that you don't have HDFS as your underlying filesystem.
* From your user ( `hduser`) it seems that you're running on HDInsight. For the `teragen` and `terasort` you should use your own user instead of the default one. The idea of this exercise is that you also create a home directory for your user.
* Please format code and command outputs appropriately in Markdown.
* When running a command you should also show its output.
* You need a good reason when pushing binary files into Git. Normally this isn't a good idea, especially for JARs. In an enterprise setup you will use something such as Nexus or Artifactory for distributing your artifacts.
* You should use a `.gitignore` file. This prevents you from submitting unwanted files and directories, such as the `target` directory.
* Your Maven project doesn't build. You should add all necessary dependencies for a successful build.
* You are using the old MapReduce API for your job (`org.apache.hadoop.mapred`). Use `org.apache.hadoop.mapreduce` instead.

Open points:

* Re-run `teragen` and `terasort` with your own user (named after your GitHub handle).
* Packaging of the `WordCount` application into a Maven project.
* Update your `WordCount` class to use the new MapReduce API.
